Post: why content-centric platforms depend heavily on caching
handsonarchitects/blog pull request #11
Opened 2023-10-15 20:40 UTC by malaskowski

2023-10-16 20:26 UTC, tomaszmichalak requested changes

2023-10-16 20:26 UTC, tomaszmichalak commented on content/blog/2023/why-content-centric-architectures-depend-on-caching/index.md
> +For example, in the Adobe Experience Manager (AEM), the caching happens on the Dispatcher level (Apache Server module). The Dispatcher proxies the request to AEM, caches the responses, and serves the
```suggestion
For example, in the Adobe Experience Manager (AEM), the caching happens on the Dispatcher level (Apache Server module). The Dispatcher proxies all the requests to AEM Publish instances, caches the responses, and serves them to the end users.
```

2023-10-16 20:26 UTC, tomaszmichalak commented on content/blog/2023/why-content-centric-architectures-depend-on-caching/index.md
> +For example, in the Adobe Experience Manager (AEM), the caching happens on the Dispatcher level (Apache Server module). The Dispatcher proxies the request to AEM, caches the responses, and serves the
Maybe you should mention that the hardest part of Dispatcher caching are invalidation rules. They depend on complex content relations (PDP pages and PLP pages etc) and .stat files. More here: https://experienceleague.adobe.com/docs/experience-manager-dispatcher/using/configuring/dispatcher-configuration.html?lang=en

When we refer to AEM, we must be very precise.

2023-10-16 20:26 UTC, tomaszmichalak commented on content/blog/2023/why-content-centric-architectures-depend-on-caching/index.md
> +To make things more clear, let's work with some examples. We will use a simple Product Details Page reference. The solution involves the CMS, which is the source of content and layouts of pages. Prod
```suggestion
To make things more clear, let's work with some example. We will use a simple Product Details Page reference. The solution involves the CMS, which is the source of content and layouts of pages. Product Information Management (PIM) system is the source of product data presented on the product pages.
```

2023-10-17 19:02 UTC, malaskowski commented on content/blog/2023/why-content-centric-architectures-depend-on-caching/index.md
> +For example, in the Adobe Experience Manager (AEM), the caching happens on the Dispatcher level (Apache Server module). The Dispatcher proxies the request to AEM, caches the responses, and serves the
I will stick to the previous version.

2023-10-17 20:15 UTC, merged